--ozone-platform-hint=auto
--enable-features=WaylandWindowDecorations,VaapiVideoDecoder,VaapiVideoDecodeLinuxGL
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--disable-features=UseChromeOSDirectVideoDecoder
--password-store=gnome-libsecret
