[FileDialog]
history=file:///usr/bin, file:///home/asephs/.steam/steamcmd, file:///home/asephs, file:///home/asephs/GOG Games/RimWorld/game, file:///home/asephs/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios, file:///home/asephs/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Config
lastVisited=file:///home/asephs/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Config
qtVersion=5.15.2
shortcuts=file:, file:///home/asephs
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=List
