monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.*"
      }
    ]
    actions = {
      create-stream = {
        media.class = "Audio/Source"
        audio.rate = 48000
        audio.channels = 1
        node.description = "Noise Suppression for Voice"
        filter.graph = {
          nodes = [
            {
              type = "ladspa"
              name = "rnnoise"
              plugin = "librnnoise_ladspa.so"
              label = "noise_suppressor_mono"
              control = {
                "VAD Threshold (%)" = 50
              }
            }
          ]
        }
      }
    }
  }
]
